# Default values for npmhello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: arsbklogin
image:
  repository: azeastusbspdevnewobwacr.azurecr.io/arsbklogin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
containerPort: 8090


service:
  name: login
  type: LoadBalancer
  port: 8090
  targetPort: 8090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
